version: '3.8'

services:
  backend:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_DATABASE=seu_marketplace
    command: bash -c "npm install && adonis migration:run && npm run dev"

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: seu_marketplace
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: