version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: seu_marketplace
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    network_mode: bridge

volumes:
  db_data: